name: py36_ipynb
channels:
  - conda-forge
dependencies:
  - python=3.6
  - ipyvolume==0.5.1
  - ipywidgets>=7.4.0
  - ipywebrtc>=0.4
  - pip
  - pip:
      - matplotlib>=3
      - Pillow
      - imageio
      - numpy
      - numpy-stl
      - termcolor
      - colored
      - trimesh==2.36.19
      - scipy
      - scikit-image>=0.13
      - requests
      - notebook>=5.3
      - vtk>=8
      - xvfbwrapper
